--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BabosApple/Teleportation-Bow
build-by-default: true
branches:
- main
projects:
  Teleportation-Bow:
    path: ""
    icon: "icon.webp"
...
